### ISSUE TITLE
Apple OCSP responder blocked

### ISSUE THREAD

**Issue by WaLLy3K** [ReddestDream/reddestdream.github.io#2]
Opening a ticket on behalf of @madsky [opened a ticket on my repo to mention](https://github.com/WaLLy3K/wally3k.github.io/issues/28):

> ocsp.apple.com is blocked by this list: https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts

> Since this is a crypto service it might be worth flagging as a site worth whitelisting. The owner of reddestdream has no obvious method of contacting them, but since the purpose of their list appears to relate to jailbreaking iPhones I'm not sure it's an accidental entry or they'd be interested in removing it.

**Comment by ReddestDream** [comment]
Yeah. That's all it was. It was to an old JB that some people are still on. I don't work on this project much anymore given that content blockers pretty much do all I need on iOS, and I haven't had a jailbroken device in a while.

I really didn't want to add it since there's nothing malicious or ad-related about the host, but given that if I didn't, it would cause some people's jailbreak certs to expire, I didn't have much choice at the time. You wouldn't want to include it for anything outside of iOS devices with JBs based on expired certificates. Eventually if I work on this project again and I can set it up to not be installable on devices with older iOS versions, I'll end up removing it. Thx.
